# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='location',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='address',
            field=models.CharField(default=0, max_length=150, verbose_name='机构地址'),
        ),
    ]
