# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-30 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_personal_manage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_manage',
        ),
    ]
